FROM docker.io/debian:bookworm-slim AS builder

WORKDIR /vector
COPY vector.tar.gz ./

RUN tar -xvf vector.tar.gz --strip-components=2 \
    && mkdir -p /var/lib/vector

FROM docker.io/debian:bookworm-slim

# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.url="https://vector.dev"
LABEL org.opencontainers.image.source="https://github.com/vectordotdev/vector"
LABEL org.opencontainers.image.documentation="https://vector.dev/docs"

# we want the latest versions of these
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates tzdata systemd liblldpctl-dev && rm -rf /var/lib/apt/lists/*
COPY klx.tar.gz /opt/klx.tar.gz
RUN tar -xvf /opt/klx.tar.gz -C /opt
RUN rm -rf /opt/klx.tar.gz
COPY --from=builder /vector/bin/* /usr/local/bin/
COPY --from=builder /vector/config/vector.yaml /etc/vector/vector.yaml

# Smoke test
RUN ["vector", "--version"]

ENTRYPOINT ["/usr/local/bin/vector"]