# FROM docker.io/debian:bookworm-slim AS builder
FROM harbor.zhejianglab.com/zjnc-tech/debian:bookworm-slim AS builder

WORKDIR /vector
COPY vector.tar.gz ./

RUN tar -xvf vector.tar.gz --strip-components=2 \
    && mkdir -p /var/lib/vector

FROM harbor.zhejianglab.com/zjnc-tech/debian:bookworm-slim

# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.url="https://vector.dev"
LABEL org.opencontainers.image.source="https://github.com/vectordotdev/vector"
LABEL org.opencontainers.image.documentation="https://vector.dev/docs"

# 安装 LLDP 和 SNMP 客户端及依赖
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates \
       tzdata \
       systemd \
       lldpd \
       snmp \
       libsnmp-dev \
       liblldpctl-dev \
    && rm -rf /var/lib/apt/lists/*

# 拷贝 Vector 可执行文件和默认配置
COPY --from=builder /vector/bin/* /usr/local/bin/
COPY --from=builder /vector/config/vector.yaml /etc/vector/vector.yaml

# Smoke test
RUN ["vector", "--version"]

ENTRYPOINT ["/usr/local/bin/vector"]