// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 3.20.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `pod_resources_types.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:v1alpha1.ListPodResourcesRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ListPodResourcesRequest {
    // special fields
    // @@protoc_insertion_point(special_field:v1alpha1.ListPodResourcesRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ListPodResourcesRequest {
    fn default() -> &'a ListPodResourcesRequest {
        <ListPodResourcesRequest as ::protobuf::Message>::default_instance()
    }
}

impl ListPodResourcesRequest {
    pub fn new() -> ListPodResourcesRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ListPodResourcesRequest>(
            "ListPodResourcesRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ListPodResourcesRequest {
    const NAME: &'static str = "ListPodResourcesRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ListPodResourcesRequest {
        ListPodResourcesRequest::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ListPodResourcesRequest {
        static instance: ListPodResourcesRequest = ListPodResourcesRequest {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ListPodResourcesRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ListPodResourcesRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ListPodResourcesRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListPodResourcesRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:v1alpha1.ListPodResourcesResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ListPodResourcesResponse {
    // message fields
    // @@protoc_insertion_point(field:v1alpha1.ListPodResourcesResponse.pod_resources)
    pub pod_resources: ::std::vec::Vec<PodResources>,
    // special fields
    // @@protoc_insertion_point(special_field:v1alpha1.ListPodResourcesResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ListPodResourcesResponse {
    fn default() -> &'a ListPodResourcesResponse {
        <ListPodResourcesResponse as ::protobuf::Message>::default_instance()
    }
}

impl ListPodResourcesResponse {
    pub fn new() -> ListPodResourcesResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "pod_resources",
            |m: &ListPodResourcesResponse| { &m.pod_resources },
            |m: &mut ListPodResourcesResponse| { &mut m.pod_resources },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ListPodResourcesResponse>(
            "ListPodResourcesResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ListPodResourcesResponse {
    const NAME: &'static str = "ListPodResourcesResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.pod_resources.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.pod_resources {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.pod_resources {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ListPodResourcesResponse {
        ListPodResourcesResponse::new()
    }

    fn clear(&mut self) {
        self.pod_resources.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ListPodResourcesResponse {
        static instance: ListPodResourcesResponse = ListPodResourcesResponse {
            pod_resources: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ListPodResourcesResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ListPodResourcesResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ListPodResourcesResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListPodResourcesResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:v1alpha1.PodResources)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PodResources {
    // message fields
    // @@protoc_insertion_point(field:v1alpha1.PodResources.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:v1alpha1.PodResources.namespace)
    pub namespace: ::std::string::String,
    // @@protoc_insertion_point(field:v1alpha1.PodResources.containers)
    pub containers: ::std::vec::Vec<ContainerResources>,
    // special fields
    // @@protoc_insertion_point(special_field:v1alpha1.PodResources.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PodResources {
    fn default() -> &'a PodResources {
        <PodResources as ::protobuf::Message>::default_instance()
    }
}

impl PodResources {
    pub fn new() -> PodResources {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &PodResources| { &m.name },
            |m: &mut PodResources| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "namespace",
            |m: &PodResources| { &m.namespace },
            |m: &mut PodResources| { &mut m.namespace },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "containers",
            |m: &PodResources| { &m.containers },
            |m: &mut PodResources| { &mut m.containers },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PodResources>(
            "PodResources",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PodResources {
    const NAME: &'static str = "PodResources";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.namespace = is.read_string()?;
                },
                26 => {
                    self.containers.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if !self.namespace.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.namespace);
        }
        for value in &self.containers {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if !self.namespace.is_empty() {
            os.write_string(2, &self.namespace)?;
        }
        for v in &self.containers {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PodResources {
        PodResources::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.namespace.clear();
        self.containers.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PodResources {
        static instance: PodResources = PodResources {
            name: ::std::string::String::new(),
            namespace: ::std::string::String::new(),
            containers: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PodResources {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PodResources").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PodResources {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PodResources {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:v1alpha1.ContainerResources)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ContainerResources {
    // message fields
    // @@protoc_insertion_point(field:v1alpha1.ContainerResources.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:v1alpha1.ContainerResources.devices)
    pub devices: ::std::vec::Vec<ContainerDevices>,
    // special fields
    // @@protoc_insertion_point(special_field:v1alpha1.ContainerResources.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ContainerResources {
    fn default() -> &'a ContainerResources {
        <ContainerResources as ::protobuf::Message>::default_instance()
    }
}

impl ContainerResources {
    pub fn new() -> ContainerResources {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &ContainerResources| { &m.name },
            |m: &mut ContainerResources| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "devices",
            |m: &ContainerResources| { &m.devices },
            |m: &mut ContainerResources| { &mut m.devices },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ContainerResources>(
            "ContainerResources",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ContainerResources {
    const NAME: &'static str = "ContainerResources";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.devices.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        for value in &self.devices {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        for v in &self.devices {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ContainerResources {
        ContainerResources::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.devices.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ContainerResources {
        static instance: ContainerResources = ContainerResources {
            name: ::std::string::String::new(),
            devices: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ContainerResources {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ContainerResources").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ContainerResources {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ContainerResources {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:v1alpha1.ContainerDevices)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ContainerDevices {
    // message fields
    // @@protoc_insertion_point(field:v1alpha1.ContainerDevices.resource_name)
    pub resource_name: ::std::string::String,
    // @@protoc_insertion_point(field:v1alpha1.ContainerDevices.device_ids)
    pub device_ids: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:v1alpha1.ContainerDevices.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ContainerDevices {
    fn default() -> &'a ContainerDevices {
        <ContainerDevices as ::protobuf::Message>::default_instance()
    }
}

impl ContainerDevices {
    pub fn new() -> ContainerDevices {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "resource_name",
            |m: &ContainerDevices| { &m.resource_name },
            |m: &mut ContainerDevices| { &mut m.resource_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "device_ids",
            |m: &ContainerDevices| { &m.device_ids },
            |m: &mut ContainerDevices| { &mut m.device_ids },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ContainerDevices>(
            "ContainerDevices",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ContainerDevices {
    const NAME: &'static str = "ContainerDevices";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.resource_name = is.read_string()?;
                },
                18 => {
                    self.device_ids.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.resource_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.resource_name);
        }
        for value in &self.device_ids {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.resource_name.is_empty() {
            os.write_string(1, &self.resource_name)?;
        }
        for v in &self.device_ids {
            os.write_string(2, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ContainerDevices {
        ContainerDevices::new()
    }

    fn clear(&mut self) {
        self.resource_name.clear();
        self.device_ids.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ContainerDevices {
        static instance: ContainerDevices = ContainerDevices {
            resource_name: ::std::string::String::new(),
            device_ids: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ContainerDevices {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ContainerDevices").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ContainerDevices {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ContainerDevices {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x19pod_resources_types.proto\x12\x08v1alpha1\"\x19\n\x17ListPodResour\
    cesRequest\"W\n\x18ListPodResourcesResponse\x12;\n\rpod_resources\x18\
    \x01\x20\x03(\x0b2\x16.v1alpha1.PodResourcesR\x0cpodResources\"~\n\x0cPo\
    dResources\x12\x12\n\x04name\x18\x01\x20\x01(\tR\x04name\x12\x1c\n\tname\
    space\x18\x02\x20\x01(\tR\tnamespace\x12<\n\ncontainers\x18\x03\x20\x03(\
    \x0b2\x1c.v1alpha1.ContainerResourcesR\ncontainers\"^\n\x12ContainerReso\
    urces\x12\x12\n\x04name\x18\x01\x20\x01(\tR\x04name\x124\n\x07devices\
    \x18\x02\x20\x03(\x0b2\x1a.v1alpha1.ContainerDevicesR\x07devices\"V\n\
    \x10ContainerDevices\x12#\n\rresource_name\x18\x01\x20\x01(\tR\x0cresour\
    ceName\x12\x1d\n\ndevice_ids\x18\x02\x20\x03(\tR\tdeviceIdsB/Z-k8s.io/ku\
    belet/pkg/apis/podresources/v1alpha1b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(ListPodResourcesRequest::generated_message_descriptor_data());
            messages.push(ListPodResourcesResponse::generated_message_descriptor_data());
            messages.push(PodResources::generated_message_descriptor_data());
            messages.push(ContainerResources::generated_message_descriptor_data());
            messages.push(ContainerDevices::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}